/** Declaration file generated by dts-gen */
/** 自定义模块声明 */
declare module "qcloudsms_js";
declare module 'koa-nunjucks-2';
declare module 'koa-socket';
declare module 'koa-bodyparser';
declare module 'koa-redis';
declare module 'mongoose-auto-increment-fix';


